name: CI Workflow

on:
  push:
    branches: [ main, master ]

jobs: 
    continues-integration:
      runs-on: ubuntu-latest

      steps: 
       - name: checkout
         uses: actions/checkout@v4

       - name: setup node js
         uses: actions/setup-node@v4
         with: 
          node-version: '20'
          cache: 'npm'

       - name: install-dependancy
         uses: npm install

       - name: run test
         uses: npm test

       - name: build project
         uses: npm run build

      

      
  
